### PR TITLE
trying to fix the docker network issue in travis

### PR DESCRIPTION
**Pull request by quentinus95**

### CODE REVIEW

**Comment by quentinus95** [comment]
@PLoic it seems like using the default docker given address (172.17.0.2) is solving our curl issue.

see https://github.com/docker/docker/issues/13847

**Comment by PLoic** [comment]
Great ! But I just restart 2 times the CI and I have one fail and one working, it's a little bit strange.

**Comment by quentinus95** [comment]
Ok, I will try something else on this branch.

**Comment by PLoic** [comment]
We not have the same error : https://travis-ci.org/dldl/sphinx-server/builds/177160275

**Comment by quentinus95** [comment]
I will try a `arp -d 172.17.0.2` on the hosting machine (not the docker container) to check if it solves anything.

**Comment by quentinus95** [comment]
It should be OK now. Can you confirm ? Thx

**Comment by PLoic** [comment]
Sounds good for me

**Review by PLoic — APPROVED** [review]

**Pull request merged**
