### PR TITLE
Support Python 3

### PR DESCRIPTION
**Pull request by sp1thas**
This PR is about migrate sphinx-server to Python 3 (related with #34 )

Due to the fact that I'm not familiar with Travis please take a closer look at `.travis.yml` file, I'm not sure if it is configured right.

### CODE REVIEW

**Comment by quentinus95** [comment]
Hi @sp1thas, thanks for your contribution. When testing the new image, I'm getting the following error:

```
Traceback (most recent call last):
  File "/opt/sphinx-server/server.py", line 101, in <module>
    key = base64.b64encode(auth)
  File "/usr/local/lib/python3.8/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'
```

When used with the following configuration:

```yml
autobuild: false
credentials:
  username: hello
  password: world
```

**Comment by quentinus95** [comment]
I'm also getting the following warnings:

```
/opt/sphinx-server/server.py:64: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  configuration = yaml.load(config_stream)
/opt/sphinx-server/server.py:68: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  configuration.update(yaml.load(custom_stream))
```

**Comment by sp1thas** [comment]
Hi @quentinus95 

last commit seems to fix the issues.

**Comment by quentinus95** [comment]
Looks good to me, thanks @sp1thas!

**Pull request merged**
