### PR TITLE
autobuild enabled by default

### PR DESCRIPTION
**Pull request by quentinus95**

### CODE REVIEW

**Comment by quentinus95** [comment]
This PR enable autobuild as default behavior (fixes for sphinx-preview).

**Comment by PLoic** [comment]
Good for me

**Review by PLoic — APPROVED** [review]

**Comment by quentinus95** [comment]
@PLoic I've rolled back Alpine to 3.5 as 3.6 seems buggy.

This may be merged now.

**Comment by quentinus95** [comment]
Thanks @PLoic !

**Pull request merged**
